Repository afterssafy6/afterssafy6, pull requests merged in 2022-06, with the labels that each got.

#10 [1주차] 유혜승
  .gitignore
  1주차/BOJ_1013_Contact/Boj_1013_Contact_hyeseung.java
  1주차/BOJ_1744_수_묶기/BOJ_1744_수_묶기_hyeseung.java
  1주차/BOJ_2075_N번째큰수/BOJ_2075_N번째큰수_hyeseung.java
  1주차/BOJ_2108_통계학/BOJ_2108_통계학_hyeseung.java
  1주차/BOJ_2470_두_용액/Boj_2470_두_용액_hyeseung.java
Labels: 코드제출

#9 [1주차] 김민성
  .DS_Store
  1주차/.DS_Store
  1주차/BOJ_1234_크리스마스 트리/BOJ_1234_크리스마스트리_minsung.java
  1주차/BOJ_1744_수 묶기/BOJ_1744_수 묶기_김민성.java
  1주차/BOJ_20055_컨베이어 벨트 위의 로봇/BOJ_20055_컨베이어 벨트 위의 로봇_김민성.java
  1주차/BOJ_2075_N번째 큰 수/BOJ_2075_N번째 큰 수_김민성.java
  1주차/BOJ_2108_통계학/BOJ_2108_통계학_김민성.java
Labels: 코드제출

#12 [1주차] 이소현
  1주차/BOJ_1013_Contact/BOJ_1013_Contact_sohyeon.java
  1주차/BOJ_1744_수_묶기/BOJ_1744_수_묶기_sohyeon.java
  1주차/BOJ_20055_컨베이어_벨트_위의_로봇/BOJ_20055_컨베이어_벨트_위의_로봇_sohyeon.java
  1주차/BOJ_2075_N번째_큰_수/BOJ_2075_N번째_큰_수_sohyeon.java
  1주차/BOJ_2108_통계학/BOJ_2108_통계학_sohyeon.java
  1주차/BOJ_2470_두_용액/BOJ_2470_두_용액_sohyeon.java
Labels: 코드제출

#22 2주차 사항 추가
  README.md
Labels: 문서작업

#25 [3주차] 김민성
  3주차/BOJ_1041_주사위/BOJ_1041_주사위_김민성.java
  3주차/BOJ_11000_강의실_배정/BOJ_11000_강의실_배정_김민성.java
  3주차/BOJ_11509_풍선_맞추기/BOJ_11509_풍선_맞추기_김민성.java
  3주차/BOJ_1197_최소_스패닝_트리/BOJ_1197_최소_스패닝_트리_김민성.java
  3주차/BOJ_13549_숨바꼭질_3/BOJ_13549_숨바꼭질_3_김민성.java
  3주차/BOJ_2206_벽_부수고_이동하기/BOJ_2206_벽_부수고_이동하기_김민성.java
Labels: 코드제출

#29 [3주차] 최정민
  3주차/BOJ_1041_주사위/BOJ_1041_주사위_최정민.py
  3주차/BOJ_11000_강의실_배정/BOJ_11000_강의실_배정_최정민.py
  3주차/BOJ_11509_풍선_맞추기/BOJ_11509_풍선_맞추기_최정민.py
  3주차/BOJ_1197_최소_스패닝_트리/BOJ_1197_최소_스패닝_트리_최정민.py
  3주차/BOJ_13549_숨바꼭질_3/BOJ_13549_숨바꼭질_3_최정민.py
  3주차/BOJ_2206_벽_부수고_이동하기/BOJ_2206_벽_부수고_이동하기_최정민.py
Labels: 코드제출

#23 [3주차] 백준 :: 그래프 이론, 그리디
  3주차/BOJ_1041_주사위/BOJ_1041_주사위_김민성.java
  3주차/BOJ_1041_주사위/BOJ_1041_주사위_김형준.cpp
  3주차/BOJ_1041_주사위/BOJ_1041_주사위_이소현.java
  3주차/BOJ_1041_주사위/BOJ_1041_주사위_최정민.py
  3주차/BOJ_1041_주사위/README.md
  3주차/BOJ_11000_강의실_배정/BOJ_11000_강의실_배정_김민성.java
  3주차/BOJ_11000_강의실_배정/BOJ_11000_강의실_배정_김형준.cpp
  3주차/BOJ_11000_강의실_배정/BOJ_11000_강의실_배정_서지원.py
  3주차/BOJ_11000_강의실_배정/BOJ_11000_강의실_배정_최정민.py
  3주차/BOJ_11000_강의실_배정/README.md
  3주차/BOJ_11509_풍선_맞추기/BOJ_11509_풍선_맞추기_김민성.java
  3주차/BOJ_11509_풍선_맞추기/BOJ_11509_풍선_맞추기_김형준.cpp
  3주차/BOJ_11509_풍선_맞추기/BOJ_11509_풍선_맞추기_최정민.py
  3주차/BOJ_11509_풍선_맞추기/README.md
  3주차/BOJ_1197_최소_스패닝_트리/BOJ_1197_최소_스패닝_트리_김민성.java
  3주차/BOJ_1197_최소_스패닝_트리/BOJ_1197_최소_스패닝_트리_김형준.cpp
  3주차/BOJ_1197_최소_스패닝_트리/BOJ_1197_최소_스패닝_트리_유혜승.java
  3주차/BOJ_1197_최소_스패닝_트리/BOJ_1197_최소_스패닝_트리_최정민.py
  3주차/BOJ_1197_최소_스패닝_트리/README.md
  3주차/BOJ_13549_숨바꼭질_3/BOJ_13549_숨바꼭질_3_김민성.java
  3주차/BOJ_13549_숨바꼭질_3/BOJ_13549_숨바꼭질_3_김형준.cpp
  3주차/BOJ_13549_숨바꼭질_3/BOJ_13549_숨바꼭질_3_유혜승.java
  3주차/BOJ_13549_숨바꼭질_3/BOJ_13549_숨바꼭질_3_이소현.java
  3주차/BOJ_13549_숨바꼭질_3/BOJ_13549_숨바꼭질_3_최정민.py
  3주차/BOJ_13549_숨바꼭질_3/README.md
  3주차/BOJ_2206_벽_부수고_이동하기/BOJ_2206_벽_부수고_이동하기_김민성.java
  3주차/BOJ_2206_벽_부수고_이동하기/BOJ_2206_벽_부수고_이동하기_김형준.cpp
  3주차/BOJ_2206_벽_부수고_이동하기/BOJ_2206_벽_부수고_이동하기_최정민.py
  3주차/BOJ_2206_벽_부수고_이동하기/README.md
  3주차/README.md
Labels: 주간마감

#31 3주차 사항 추가
  README.md
Labels: 문서작업

#37 [4주차] 최정민
  4주차/PG_92334_신고_결과_받기/README.md
  4주차/PG_92335_k진수에서_소수_개수_구하기/README.md
  4주차/PG_92341_주차_요금_계산/README.md
  4주차/PG_92342_양궁대회/README.md
  4주차/PG_92343_양과_늑대/PG_92343_양과_늑대_최정민.py
  4주차/PG_92343_양과_늑대/README.md
  4주차/PG_92344_파괴되지_않은_건물/README.md
Labels: 코드제출

#32 [4주차] 프로그래머스 :: 2022 카카오 신입 공채 1차
  4주차/PG_92334_신고_결과_받기/README.md
  4주차/PG_92335_k진수에서_소수_개수_구하기/README.md
  4주차/PG_92341_주차_요금_계산/README.md
  4주차/PG_92342_양궁대회/README.md
  4주차/PG_92343_양과_늑대/README.md
  4주차/PG_92344_파괴되지_않은_건물/README.md
Labels: 주간마감

#36 [4주차] 김형준
  4주차/PG_92344_파괴되지_않은_건물/PG_92344_파괴되지_않은_건물_김형준.cpp
Labels: 코드제출

#34 [4주차] 김민성
  4주차/PG_92334_신고_결과_받기/PG_92334_신고_결과_받기_김민성.java
  4주차/PG_92335_k진수에서_소수_개수_구하기/PG_92335_k진수에서_소수_개수_구하기_김민성.java
  4주차/PG_92341_주차_요금_계산/PG_92341_주차_요금_계산_김민성.java
  4주차/PG_92342_양궁대회/PG_92342_양궁대회_김민성.java
  4주차/PG_92343_양과_늑대/PG_92343_양과_늑대_김민성.java
Labels: 코드제출

#33 [4주차] 유혜승
  4주차/PG_92335_k진수에서_소수_개수_구하기/PG_92335_k진수에서_소수_개수_구하기_유혜승.java
Labels: 코드제출
